name: background_runtime_linux
description: Linux implementation of the background_runtime plugin.
version: 0.1.0
publish_to: none
homepage: https://github.com/mixin27/background_runtime
repository: https://github.com/mixin27/background_runtime
issue_tracker: https://github.com/mixin27/background_runtime/issues

resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  background_runtime_platform_interface:
    path: ../background_runtime_platform_interface

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: BackgroundRuntimeLinuxPlugin

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
