blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/mixin27/background_runtime/discussions
    about: Please ask usage questions in Discussions.
  - name: Security Issues
    url: https://github.com/mixin27/background_runtime/security/policy
    about: Please report security vulnerabilities privately.
